# NOTE: this file is generated via 'make generate'
dependencies:
- changed-files:
  - any-glob-to-any-file:
    - go.mod
    - go.sum
    - vendor/**/*
documentation:
- changed-files:
  - any-glob-to-any-file: 
    - docs/**/*
    - examples/**/*
tooling:
- changed-files:
  - any-glob-to-any-file: 
    - .github/**/*
    - internal/tools/**/*
    - scripts/**/*
    - GNUmakefile
state-migration:
- changed-files:
  - any-glob-to-any-file: 
    - internal/services/**/migration/**/*