---
name: GoLang Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/golint.yaml'
      - 'vendor/**'
      - '**.go'

jobs:
  golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: .go-version
      - uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: 'v1.54.2'
          args: -v

  save-artifacts-on-fail:
    if: ${{ needs.golint.result }} == 'failure'
    uses: ./.github/workflows/save-artifacts.yaml

  comment-on-fail:
    if: ${{ needs.golint.result }} == 'failure'
    uses: ./.github/workflows/comment-failure.yaml
